# This is a GitLab CI/CD configuration file for AngstromCube

stages:          # List of stages for jobs, and their order of execution
  - build
  - run

build_on_JUSUF:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Set module environment"
    - module --force purge && module load Stages/2023  GCC/11.3.0  ParaStationMPI/5.8.0-1-mt imkl-FFTW/2022.1.0 CMake 
    - export MKL_ROOT=/p/software/jusuf/stages/2023/software/imkl/2022.1.0/mkl/latest/
    - echo "Start build system..."
    - rm -rf build && mkdir build && cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=~/a43
    - echo "Compiling the code..."
    - make -j install
    - cd ..
    - echo "Compile complete."
    - ls ~/a43/lib64 ~/a43/bin
  tags:         # Set tags such that we can use the shared runners of the JSC gitlab
    - jacamar
    - jusuf 
    - login     # Compile on login node
    - shell

test_on_JUSUF:   # This job also runs in the test stage.
  stage: run    # It can run at the same time as run_on_JUSUF
  script:
    - echo "Run A43 unit tests..."
    - ./a43 --test
    - echo "A43 unit tests done."
  tags:
    - jacamar
    - jusuf 
    - login
    - shell

run_on_JUSUF:   # This job also runs in the test stage.
  stage: run    # It can run at the same time as test_on_JUSUF
  script:
    - echo "Run green unit tests..."
    - ./green --test
    - echo "green unit tests done."
  tags:
    - jacamar
    - jusuf 
    - login    # ToDo Run other tests on backend --> change to compute
    - shell    # ToDo Run other tests on backend --> change to slurm
